### ISSUE TITLE
How to calibrate Pixhawk IMU and Realsense Camera? 

### ISSUE THREAD

**Issue by vislero** [url-kaist/kaistviodataset#3]
First of all, thank you for sharing your nice work.

We are also testing the VIO algorithm for autonomous flight using the Realsense D-435i.

By the way, the rosbag data you have shared publishes the Pixhawk IMU to feed these data to the VIO algorithm.

So we have two question about that. 

1. Is there any reason to use a Pixhawk IMU instead of using the D-435i's IMU?

2. And we also tried to calibrate the extrinsic transformation between the Pixhawk IMU and the D-435i's infrared camera using Kalibr, but the calibration result is not as good as when I used the D435i's IMU. Could you give me some tips for good calibration results?

In the figure below, the figure on the left is the case of calibration using the D-435i's IMU, and the result on the right is the case of using the Pixhawk's IMU.
(In the figures on the right, both the bias estimation and reprojection errors are out of bounds...)

![Screenshot from 2021-05-04 19-21-20](https://user-images.githubusercontent.com/69630044/116990373-fdd97880-ad0d-11eb-9d81-9f936af861c5.png)
![Screenshot from 2021-05-04 19-21-04](https://user-images.githubusercontent.com/69630044/116990381-003bd280-ad0e-11eb-82bc-90e393866266.png)

thank you.

regards.

**Comment by zinuok** [comment]
I also tried to use the d435i's IMU, but it showed bad performance, like your case.
So I used the IMU built into the Pixhawk.

Best regards
Jinwoo Jeon
