### ISSUE TITLE
about the topic

### ISSUE THREAD

**Issue by zoe4751** [url-kaist/kaistviodataset#4]
when I run VINS-FUSION, error is happened as shown in the picture:
![image](https://user-images.githubusercontent.com/31506909/122356427-60689a00-cf85-11eb-957d-49c385a92b1d.png)

when we run dataset "kaistviodataset", our "realsense_stereo_imu_config.yaml" is shown in the picture:
![image](https://user-images.githubusercontent.com/31506909/122356961-dd940f00-cf85-11eb-86c7-002037018b34.png)

**Comment by zinuok** [comment]
Have you tried the decompressed image topic?
The currently uploaded dataset has an image topic "compressed". 
it seems that using a compressed image topic doesn't match the version of your program.
Can you try running a separate node once and publish the compressed image as just an image?

**Comment by zinuok** [comment]
If that solves your problem, please let me know.

I uploaded the compressed version for capacity, but this seems to cause some inconvenience to you.
I will update the dataset soon by replacing compressed with just a normal image.

Sincerly,
Jinwoo Jeon

We apologize for any inconvenience.

**Comment by zoe4751** [comment]
Thank you so much for your answer. We run our program as your suggest, but it seems not work. Could you please upload the normal image one. 
I would like to you if you have the dataset including the topic of depth.
Thanks again for your help.

Sincerely,
Zoe

**Comment by zinuok** [comment]
@zoe4751 ,
Sorry for late reply.
I have updated the dataset by replacing all compressed messages with raw messages.
Could you please download it again and try it?

Sincerely,
Jinwoo Jeon
