### ISSUE TITLE
About Pixhawk 4 mini Calibration

### ISSUE THREAD

**Issue by dssdyx** [url-kaist/kaistviodataset#9]
Hi, I'm also trying to use pixhawk 4 mini + d435i for VIO. I want to know whether you calibrate sensors of pixhawk 4 mini in ground station such as QGC or MP before recording datasets. Thank you!

**Comment by zinuok** [comment]
Dear @dssdyx ,

Yes, the pixhawk4 mini sensor was calibrated via QGC for more accurate sensor information processing. (the basic calibration was performed in QGC)

Thank you 
Jinwoo Jeon

**Comment by dssdyx** [comment]
> Dear @dssdyx ,
> 
> Yes, the pixhawk4 mini sensor was calibrated via QGC for more accurate sensor information processing. (the basic calibration was performed in QGC)
> 
> Thank you Jinwoo Jeon

Thank you for your reply! Would you like to share your pixhawk 4 mini PX4 firmware and parameters?

**Comment by zinuok** [comment]
Dear @dssdyx 

I'm sorry for not getting back to you sooner. 
We don't have the PX4 firmware and parameters at this time. 

Actually, there is no special setting other than enabling vision_pose to receive GT pose from the Motion capture system. 
I hope you could easily achieve it. 
Feel free to re-open this issue or open another issue if you want. 

Thank you
Jinwoo Jeon
